CREATE TABLE viajes_internacionales (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100),
    correo VARCHAR2(100),
    edad NUMBER,
    fecha_registro DATE,
    
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario)
);